---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-eureka-server
  namespace: under76-test
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: team5-eureka-server
  template:
    metadata:
      labels:
        app: team5-eureka-server
    spec:
      containers:
      - name: team5-eureka-server
        image: k8s-vga-worker1:5000/demo-img-team5-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: team6-eureka-server
  namespace: group1-team6
spec:
  selector:
    app: team6-eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30612
  type: NodePort
