---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-eureka-server
  namespace: under76-test
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: team5-eureka-server
  template:
    metadata:
      labels:
        app: team5-eureka-server
    spec:
      containers:
      - name: team5-eureka-server
        image: k8s-vga-worker1:5000/img-team5-eureka-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8296
---
apiVersion: v1
kind: Service
metadata:
  name: team5-eureka-server
  namespace: under76-test
spec:
  selector:
    app: team5-eureka-server
  ports:
    - protocol: TCP
      port: 8296
      targetPort: 8296
      nodePort: 30512
  type: NodePort
